name: Sync Client to Private Repository

on:
  push:
    paths:
      - 'client/**'

jobs:
  sync_to_private:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Trigger Private Repository Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          repository: abhinavrathore25/Jewellery-Ecommerce
          event-type: sync-client
