name: Trigger Sync in Private Repository

on:
  push:
    branches:
      - main

jobs:
  trigger_sync:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: abhinavrathore25/Jewellery-Ecommerce
          event-type: sync-client
